---
- hosts: localhost
  become:  true
  user: vagrant
  tasks:
    - name: uninstall old versions
      yum: name={{ item }} state=absent
      with_items:
        - docker
        - docker-common
        - docker-selinux
        - docker-engine
