---
- hosts: localhost
  become:  true
  user: vagrant
  tasks:
    - name: uninstall old versions
      yum: name={{ item }} state=absent
      with_items:
        - docker
        - docker-common
        - docker-selinux
        - docker-engine
    - name: install required packge
      yum: name={{ item }} state=latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Add docker repository
      yum_repository:
        name: docker
        description: docker yum repo
        baseurl: https://download.docker.com/linux/centos/7/source/stable
        gpgkey: https://yum.dockerproject.org/gpg
        gpgcheck: yes
    - name: install required packge
      yum: "name=docker-ce state=latest"
    - name: add docker group
      group:
        name: docker
        state: present
    - name: add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
