---
- hosts: vagrants
  become:  true
  user: vagrant
  tasks:
    - name: uninstall old versions
      yum: name={{ item }} state=absent
      with_items:
        - docker
        - docker-common
        - docker-selinux
        - docker-engine
    - name: install required packge
      yum: name={{ item }} state=latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Add docker repository
      yum_repository:
        name: docker
        description: docker yum repo
        baseurl: https://download.docker.com/linux/centos/7/source/stable
        gpgkey: https://yum.dockerproject.org/gpg
        gpgcheck: yes
    - name: install required packge
      yum: "name=docker-ce state=latest"
    - name: add docker group
      group:
        name: docker
        state: present
    - name: add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
    - name: add docker to systemd
      systemd:
        name: docker
        enabled: yes
        masked: no
    - name: enable docker on chkconfig on
      service:
        name: docker
        enabled: yes
    - name: get kernel name
      shell: "uname -s"
      register: kernel_name
    - name: get cpu name
      shell: "uname -m"
      register: cpu_name
    - name: download docker-compose command
      get_url:
        url: https://github.com/docker/compose/releases/download/1.16.1/docker-compose-{{ kernel_name.stdout }}-{{ cpu_name.stdout }}
        checksum: "sha256:1804b0ce6596efe707b9cab05d74b161833ed503f0535a937dd5d17bea8fc50a"
        dest: /usr/local/bin/docker-compose
    - name: make docker-compose executable
      file:
        path: /usr/local/bin/docker-compose
        state: file
        mode: 0755
